export const words = [
    "ready", "stage", "whole", "wind", "phone", "door", "partner", "fill", "leg", "job", "lay",
    "ten", "many", "several", "position", "science", "worker", "experience", "knowledge", "surface",
    "short", "security", "most", "various", "figure", "glass", "pattern", "coach", "hard", "nearly",
    "spring", "four", "specific", "individual", "successful", "start", "early", "never", "teacher",
    "field", "middle", "throughout", "begin", "form", "feel", "difference", "citizen", "analysis",
    "although", "scene", "series", "power", "religious", "mother", "he", "table", "politics", "past",
    "today", "same", "maybe", "right", "share", "truth", "big", "military", "admit", "language", "adult",
    "red", "pay", "quality", "cup", "daughter", "player", "area", "stay", "poor", "chance", "color",
    "last", "mention", "small", "summer", "all", "sound", "officer", "interesting", "even", "buy",
    "west", "program", "air", "hit", "yourself", "discuss", "method", "necessary", "hospital", "wrong",
    "just", "boy", "research", "while", "short", "far", "total", "tonight", "that", "peace", "put",
    "simply", "raise", "culture", "watch", "body", "director", "central", "term", "relationship",
    "who", "society", "economic", "senior", "third", "author", "message", "understand", "town", "laugh",
    "strategy", "left", "reveal", "station", "record", "modern", "store", "child", "walk", "friend",
    "suffer", "blue", "sign", "include", "seven", "game", "debate", "cup", "above", "role", "share",
    "prepare", "meet", "gun", "really", "yeah", "nearly", "create", "claim", "very", "outside",
    "another", "attention", "reduce", "choose", "present", "marriage", "prevent", "institution",
    "argue", "both", "during", "quality", "house", "dog", "long", "thank", "school", "effect",
    "series", "maintain", "east", "seat", "forward", "pressure", "clear", "attack", "feeling",
    "decision", "conference", "huge", "successful", "fly", "rate", "tough", "your", "professional",
    "common", "lawyer", "available", "forget", "death", "idea", "total", "president", "year", "cultural",
    "push", "little", "better", "free", "fall", "parent", "natural", "goal", "structure", "thus",
    "evening", "space", "example", "source", "fund", "region", "suggest", "trade", "entire", "road",
    "general", "daughter", "because", "prevent", "her", "garden", "thought", "but", "personal",
    "animal", "simply", "stay", "perform", "real", "listen", "grow", "action", "community", "my",
    "ball", "news", "condition", "training", "event", "scene", "each", "public", "deep", "realize",
    "significant", "occur", "language", "brother", "sometimes", "hundred", "point", "strategy",
    "system", "raise", "police", "general", "policy", "bank", "show", "prepare", "full" ]
